const actionTypes = Object.freeze({
  // Question
  CHOOSE_ANSWER: "CHOOSE_ANSWER",
  SELECT_GROUP_QUESTION: "SELECT_GROUP_QUESTION",
  SELECT_QUESTION: "SELECT_QUESTION",
  SUBMIT_ANSWER: "SUBMIT_ANSWER",
  TIME_TODO: "TIME_TODO",
  NUMBER_OF_QUESTION: "NUMBER_OF_QUESTION",
  // Question
  // Exam
  CHOOSE_EXAM: " CHOOSE_EXAM",
  CHOOSE_EXAM_TIME: "CHOOSE_EXAM_TIME",
  // Exam

  CLEAR_DATA : "CLEAR_DATA"
});

export default actionTypes;
